### ISSUE TITLE
Keep track of permissions (ask again in case not provided)

### ISSUE THREAD

**Issue by shkurtagashi** [shkurtagashi/longtermstudy#25] opened 2018-10-24 09:30 UTC

**Comment by bianca-stancu** [comment] 2018-10-27 08:19
@shkurtagashi the solution I provided in my last commit works for notifications, but I think the issue is that the function ` isUsageAccessServiceEnabled()` from `MainActivity` doesn't actually figure out whether it's activated or not, it always returns false to me.

**Comment by shkurtagashi** [comment] 2018-10-27 10:13
Yes, I remember having similar issues with this permission. Actually, I've read and experienced other issues with the UsageStatsManager in general. I think right now is not very robust. I suggest we only ask in the begining for this permission and we don't check for it anymore. It will be our responsibility to check again with participants whether they have enabled it or not.

**Comment by bianca-stancu** [comment] 2018-10-27 17:03
That's the current behaviour, the temporary fix 😄 
Would you like to close this for now or keep it open until we find something better?

**Comment by shkurtagashi** [comment] 2018-10-28 18:43
We can close this now, I don't believe we will find a better solution in the near future :D.

**Closed** 2018-10-28 18:50 UTC
